spring:
  profiles:
    active: dev
  application:
    name: csvLoader
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:csv-db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: false
jakarta:
  persistence:
    jdbc:
      url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:csv-db}
      username: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:postgres}